---
- name: Install packages through look
  hosts: localhost
  vars:
    packages: [ftp, telnet]

  tasks:
    - name: Install packages
      yum:
        name: "{{ items }}"
        state: present
      with_items: "{{ packages }}"



